{
 "title": "IoT Campus - Groupe 02",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Température en temps réel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n|> range(start: -24h)\r\n|> filter(fn: (r) => r._measurement == \"capteurs\")\r\n|> filter(fn: (r) => r._field == \"température\")"
    }
   ]
  },
  {
   "title": "Température actuelle",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n|> range(start: -24h)\r\n|> filter(fn: (r) => r._measurement == \"capteurs\")\r\n|> filter(fn: (r) => r._field == \"température\")\r\n|> last()"
    }
   ]
  },
  {
   "title": "Moyenne 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n|> range(start: -24h)\r\n|> filter(fn: (r) => r._measurement == \"capteurs\")\r\n|> filter(fn: (r) => r._field == \"température\")\r\n|> mean()"
    }
   ]
  }
 ]
}