# =============================================================================
# Configuration Mosquitto -- Stack MING IoT
# Cours : Internet des Objets -- Mastere 1 Ynov
#
# Ce fichier est monte en lecture seule dans le conteneur Docker.
# Chemin dans le conteneur : /mosquitto/config/mosquitto.conf
# =============================================================================

# --- Listener ---
# Port 1883 : MQTT standard (non chiffre)
# Suffisant pour un reseau local isole (TP en salle de cours)
listener 1883

# --- Authentification ---
# allow_anonymous true : pas de login/mot de passe requis
# Acceptable en TP sur reseau local. En production, utiliser un fichier password.
allow_anonymous true

# --- Persistance ---
# Les messages retenus et les souscriptions survivent au redemarrage du broker
persistence true
persistence_location /mosquitto/data/

# --- Logs ---
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
