# mosquitto.conf -- Configuration Mosquitto (stack MING)
# Modifie en S8 pour activer l'authentification et le TLS

# ---------------------------------------------------------------------------
# LISTENER 1 : Port 1883 (non chiffré -- désactiver après S8)
# ---------------------------------------------------------------------------
listener 1883
# TODO (S8 étape A) : passer à false après avoir créé le fichier passwd
allow_anonymous true

# TODO (S8 étape A) : décommenter après avoir créé le fichier passwd
# password_file /mosquitto/config/passwd

# ---------------------------------------------------------------------------
# LISTENER 2 : Port 8883 (TLS -- activer en S8)
# ---------------------------------------------------------------------------
# TODO (S8 étape B) : décommenter et configurer le TLS
#
# listener 8883
# allow_anonymous false
# password_file /mosquitto/config/passwd
# cafile /mosquitto/certs/ca.crt
# certfile /mosquitto/certs/server.crt
# keyfile /mosquitto/certs/server.key
# tls_version tlsv1.3
# require_certificate false

# ---------------------------------------------------------------------------
# Persistance des messages
# ---------------------------------------------------------------------------
persistence true
persistence_location /mosquitto/data/

# ---------------------------------------------------------------------------
# Journaux
# ---------------------------------------------------------------------------
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
